# This is a docker-compose file all workers and sub-services associated with the project.

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/volumes/redis:/data
    networks:
      - redis-network

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - ./data/volumes/redis-insight:/db
    networks:
      - redis-network
    depends_on:
      - redis
  
  flower:
    image: mher/flower:latest
    ports:
      - "5555:5555"
    volumes:
      - ./data/volumes/flower:/data
    networks:
      - redis-network
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - redis-insight
  
  av2-dataset:
    build:
      context: ./workers/av2_datasets
    command: celery -A app worker --loglevel=info -Q av2_queue
    volumes:
      - ./logs:/logs
      - ./data:/data:ro
      - ./data/interim:/data/interim:rw
    networks:
      - redis-network
    environment:
      - AV2_CELERY_BASE_URL=redis://redis:6379/
      - AV2_CELERY_DATABASE_NUMBER=0
      - AV2_CELERY_LOG_DIR=/logs
      - PYTHONPATH=/app
    depends_on:
      - redis
      - redis-insight
      - flower
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '1'

  waymo-open-dataset:
    build:
      context: ./workers/waymo_datasets
    command: celery -A app worker --concurrency=2 --loglevel=info -Q waymo_queue
    volumes:
      - ./logs:/logs
      - ./data:/data:ro
      - ./data/interim:/data/interim:rw
    networks:
      - redis-network
    environment:
      - WAYMO_CELERY_BASE_URL=redis://redis:6379/
      - WAYMO_CELERY_DATABASE_NUMBER=0
      - WAYMO_CELERY_LOG_DIR=/logs
      - PYTHONPATH=/app
    depends_on:
      - redis
      - redis-insight
      - flower
    deploy:
      replicas: '2'
      resources:
        limits:
          cpus: '2'
        reservations:
          cpus: '1'
    profiles:
      - linux

networks:
  redis-network:
    driver: bridge