# This is a stand-alone docker compose file for testing/trying Agroverse Dataset - AV2.
# To use this simply run `docker-compose up` and attach the container to your editor.

services:

  redis:
    image: redis:latest
    container_name: vscode-redis
    ports:
      - "6378:6379"
    volumes:
      - ../../data/volumes/vscode-redis:/data
    networks:
      - vscode-redis-network

  av2-open-dataset:
    image: sdc-av2-dataset:latest
    container_name: vscode-av2-dataset
    volumes:
      - .:/app
      - ../../logs:/logs
      - ../../data:/data:ro
      - ../../data/interim:/data/interim:rw
    networks:
      - vscode-redis-network
    working_dir: /app
    environment:
      - AV2_CELERY_BASE_URL=redis://redis:6379/
      - AV2_CELERY_DATABASE_NUMBER=0
      - AV2_CELERY_LOG_DIR=/logs
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: /bin/bash
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '1'
    tty: true
    stdin_open: true

networks:
  vscode-redis-network:
    driver: bridge